### ISSUE TITLE
No Slack notifications being sent by plugin

### ISSUE THREAD

**Issue by christamlyn-bridge** [gmazzo/gocd-build-watcher-plugin#1]
Hi

I have installed the plugin in GO CD, installed in out slack team and configured with the API key.  But no Slack notifications have ever been sent by the plugin.

Looking at the logs I can see it reading the pipelines but log entry seems to state its non final.  Is there a way we can debug to see why no notifications are sent?

Using GO CD version: 17.2.0 

```
2017-09-07 10:43:48,045  INFO [73@MessageListener for PluginNotificationListener] BuildWatcherPlugin:52 - Ignoring non final state: stage=Company.Api/Release, stage=UNKNOWN
2017-09-07 10:46:15,145  INFO [73@MessageListener for PluginNotificationListener] BuildWatcherPlugin:52 - Ignoring non final state: stage=Company.Api.EndToEndTest.Test/Deploy, stage=UNKNOWN
```

What is a "non final state"?  My understanding is that a notification would be sent if any step in a pipeline failed, is that correct?

**Comment by gmazzo** [comment]
Hi! I can add some logs, but can you tell me what is the current status of your jobs? are they in red/greed?

PS: let me know if your GoCD is public, so I can take a look at the jobs statuses directly.

**Comment by christamlyn-bridge** [comment]
Unfortunately its private.  We have 100's of pipelines so pretty much one in every state you could imagine.

After installing the plugin I deliberately failed a pipeline with a failing test and then resolved with another checkin.  No notifications were sent on either action.

**Comment by gmazzo** [comment]
Which version of GoCD are you using?

The logger name is `com.github.gmazzo.gocd.BuildWatcherPlugin` and it uses the native GoCD system. I'm digging right now on how to increase the log level in GoCD (which seems to be in `INFO`), but if you know how to do it, all the requests are logged in `DEBUG` level.

**Comment by christamlyn-bridge** [comment]
Using GO CD version: 17.2.0 on Ubuntu (don't think that is important)

**Comment by christamlyn-bridge** [comment]
found this on the api/support page:

`` {
        "message": "Notification update failed for plugin: build-watcher.notifier",
        "detail": "Interaction with plugin with id \u0027build-watcher.notifier\u0027 implementing \u0027notification\u0027 extension failed while requesting for \u0027stage-status\u0027. Reason: [java.io.IOException: Server returned HTTP response code: 401 for URL: http://localhost:8153/go/api/pipelines/Company.PupilRegistrar.Promote.QA.Uganda/instance/216]",
        "level": "ERROR"
      }
``

**Comment by gmazzo** [comment]
Good catch, seems the the username/password for communicating with GoCD API is not working, have you configured it?
https://github.com/gmazzo/gocd-build-watcher-plugin#access-go-server-api

I just noted a snapshot of that step is missing, I'm going to add it.

**Comment by christamlyn-bridge** [comment]
yes, and its the correct username and password.  The fact that the log from the plugin is reading my pipelines and status could only work if its authenticating.  So I'm confused to what that means.

There is also only one exception, I would expect lots, one per pipeline

**Comment by gmazzo** [comment]
Try access the http://localhost:8153/go/api/pipelines/Company.PupilRegistrar.Promote.QA.Uganda/instance/216 from you web browser, with the API credentials (not your credentials, the ones you have setup in the plugin config) and let me know

**Comment by christamlyn-bridge** [comment]
If I log into go with the same credentials as entered into the plugin I can access that pipeline.  Not sure why its localhost, as the Base Url I entered is the DNS name of the server.

**Comment by gmazzo** [comment]
It's localhost, because the plugin runs in the same JVM than GO. The base URL is for building external links (in Slack messages and emails).

Can you attach the JSON returned by the URL?

**Comment by christamlyn-bridge** [comment]
Only reluctance is that if this was the issue, I should see lots of these exceptions rather than just one.  This certainly isn't the only pipeline that has failed/fixed

```
{
    "label": "2.0.342",
    "name": "Company.PupilRegistrar.Promote.QA.Uganda",
    "natural_order": 216,
    "can_run": true,
    "stages": [
        {
            "result": "Passed",
            "jobs": [
                {
                    "state": "Completed",
                    "result": "Passed",
                    "name": "Promote",
                    "id": 138491,
                    "scheduled_date": 1504791056224
                }
            ],
            "name": "Promote",
            "rerun_of_counter": null,
            "approval_type": "success",
            "scheduled": true,
            "operate_permission": true,
            "approved_by": "changes",
            "can_run": true,
            "id": 134585,
            "counter": "1"
        }
    ],
    "id": 62161,
    "build_cause": {
        "trigger_message": "triggered by Company.PupilRegistrar/342/publishQa/1",
        "approver": "",
        "material_revisions": [
            {
                "material": {
                    "fingerprint": "713cc97b3e91bd393e8264bfcf0df6b3210834e43450717ab31fd4363c864905",
                    "description": "Company.PupilRegistrar",
                    "id": 1746,
                    "type": "Pipeline"
                },
                "modifications": [
                    {
                        "modified_time": 1504791052163,
                        "user_name": "Unknown",
                        "id": 74877,
                        "revision": "Company.PupilRegistrar/342/publishQa/1",
                        "email_address": null,
                        "comment": "Unknown"
                    }
                ],
                "changed": true
            }
        ],
        "trigger_forced": false
    },
    "preparing_to_schedule": false,
    "counter": 216,
    "comment": null
}
```

**Comment by gmazzo** [comment]
Ok, I'll check against you current version of GoCD locally and let you know. The reason you only see this once could be because GoCD disables the plugin once it crashes (due the login issue).

In the meantime and if you didn't already, can you please try to re-enter the credentials and restart the server?

**Comment by christamlyn-bridge** [comment]
ah didnt know that about GO, useful titbit.  Will try a restart

**Comment by gmazzo** [comment]
Did it work? Just tried against your version and works just fine. If you still see the 401 error, try making the API user an admin (I don't recall if that is required)

**Comment by christamlyn-bridge** [comment]
no doesnt seem to have made any difference.  The error has gone from the support page after the restart (at least for now).

User was already an admin anyway.  Did you find how to turn on debug logging?

**Comment by christamlyn-bridge** [comment]
I setup the email notifications as well, started to see

`2017-09-07 16:36:27,913  INFO [73@MessageListener for PluginNotificationListener] BuildWatcherPlugin:52 - handleStageStatus: userEmail=chris.@company.com, current=PASSED, previous=PASSED, message=null`

What does that line indicate?  I haven't got any emails, but there is a possibility I have the SMTP settings wrong.

**Comment by gmazzo** [comment]
That's ok, it just mean the the job has not changed it PASSED state in the last execution, you should see a notification triggered if it fails.

**Comment by christamlyn-bridge** [comment]
its started working, partially at least.  I don't know what changed to make it start, but closing this issue.

**Comment by cdedev** [comment]
2019-06-01 12:28:39,584 INFO  [qtp612956834-37] Stage:234 - Stage is being completed by transition id: 100
2019-06-01 12:28:39,729 WARN  [190@MessageListener for PluginNotificationMessageListener] PluginNotificationMessageListener:63 - Notification update failed for plugin: build-watcher.notifier
java.lang.RuntimeException: javax/xml/bind/DatatypeConverter
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:310)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:246)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:150)
	at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:49)
	at com.thoughtworks.go.plugin.access.notification.NotificationExtension.notify(NotificationExtension.java:84)
	at com.thoughtworks.go.server.messaging.notifications.PluginNotificationMessageListener.onMessage(PluginNotificationMessageListener.java:45)
	at com.thoughtworks.go.server.messaging.notifications.PluginNotificationMessageListener.onMessage(PluginNotificationMessageListener.java:30)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:86)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:66)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at com.github.gmazzo.gocd.BuildWatcherPlugin.fillAPIAuth(BuildWatcherPlugin.java:174)
	at com.github.gmazzo.gocd.BuildWatcherPlugin.getPipelineInstance(BuildWatcherPlugin.java:183)
	at com.github.gmazzo.gocd.BuildWatcherPlugin.handleStageStatus(BuildWatcherPlugin.java:132)
	at com.github.gmazzo.gocd.BuildWatcherPlugin.handle(BuildWatcherPlugin.java:97)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager.lambda$submitTo$0(DefaultPluginManager.java:153)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:304)
	... 9 common frames omitted
I want to send email using buid watcher plugin. But I got that error according to the log file. I am using gocd 19.4.0. Please help me how to fix that problem.
Thanks

**Comment by gmazzo** [comment]
Which version of Java are you using? It's probably because JAXB is not part of the JRE, as it couldn't find the XML parser this plugin uses: `Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter`.

Honestly, I've made this plugin several years ago and I'm not a user of GoCD anymore. Fell free to make a PR ;)
