### ISSUE TITLE
Slack Notifications being posted to general rather than user specific channel

### ISSUE THREAD

**Issue by christamlyn-bridge** [gmazzo/gocd-build-watcher-plugin#2]
The plugin is setup with no entry in "Slack Channel" so we expect the messages to be sent to individuals, but instead the messages are being posted in the General channel.

![image](https://user-images.githubusercontent.com/20814270/30215402-d34f5da0-94a7-11e7-9a28-1c44762ac510.png)

How do you match to slack users?

**Comment by gmazzo** [comment]
Let me check, and I'll let you know

**Comment by gmazzo** [comment]
Fixed, it was taking "#general" as default channel if blank. Download version 0.6 and restart GoCD. Then enter into configs and save it to update the default.

Regards!

**Comment by christamlyn-bridge** [comment]
no files on the site

https://bintray.com/gmazzo/maven/gocd-build-watcher-plugin/0.6

**Comment by gmazzo** [comment]
Check here: https://jcenter.bintray.com/com/github/gmazzo/gocd/build-watcher-plugin/0.6/
