### ISSUE TITLE
Wrong symbols shown in help text

### ISSUE THREAD

**Issue by christamlyn-bridge** [gmazzo/gocd-build-watcher-plugin#3]
![image](https://user-images.githubusercontent.com/20814270/30272499-b4c4fb32-96ec-11e7-9e5c-6d1cbab91b2d.png)

Looks like the actual symbols should be like %user% rather than the displayed @user@

etc etc

**Comment by gmazzo** [comment]
Good catch! At some point, I may be changed it I never updated the doc. I'll change it. Thanks!

**Comment by gmazzo** [comment]
Just uploaded a new version with the fix for this. Regards!
